### ISSUE TITLE
TemplatedMapProvider renamed Template is incomplete

### ISSUE THREAD

**Issue by RandomEtc** [modestmaps/modestmaps-js#14]
There are several references to TemplatedMapProvider remaining in modestmaps.js, including in the exports for node.js.

**Comment by RandomEtc** [comment]
Incidentally if you're following semver that should have been a bump to 2.x, unless you made it backwards compatible (which would have been trivial).

Just sayin'.

**Comment by migurski** [comment]
semver++.

**Comment by RandomEtc** [comment]
major++
