### ISSUE TITLE
Moving modestmaps.com here?

### ISSUE THREAD

**Issue by tmcw** [modestmaps/modestmaps-js#15]
@tristen has been doing some badass work on an MM examples site: http://tristen.ca/mm-examples/

This brings to a head one problem - that right now modestmaps.com is under stamen/modestmaps-js and we obviously can't fork into stamen, slash don't want to merge another subtree into gh-pages of modestmaps-js as is. So, sorry that it was a long annoying process to do modestmaps.com, but possibly it can be redirected to this organization? /cc @migurski @shawnbot

**Comment by tmcw** [comment]
This is being discussed in email and is in @migurski and @shawnbot 's court to do, since I cannot do things in the stamen/ organization.

**Comment by tmcw** [comment]
Doesn't look like this is live. Sigh.

**Comment by sethfitz** [comment]
Resolved in 72d5f584b56ac793898a6616ba938c680e8a247a and stamen/modestmaps-js@0e797b6b69a80b79f8f4997563595224f8699481.
