### ISSUE TITLE
Confusing repositories.

### ISSUE THREAD

**Issue by DavidLemayian** [modestmaps/modestmaps-js#20]
Hi,
I am confused as to which repository to follow\fork.. There is this one and then there is the other under stamen/modestmaps-js.
Which one is up to date or the main one?
Clarification on this would be highly appreciated.
-David.

**Comment by tmcw** [comment]
Hi David,

This is the new official repository; we'll be adding a 'moved' notice to the other one shortly.

**Comment by DavidLemayian** [comment]
Cool. Thanks. And I think this is some great work. Kudos!
