### ISSUE TITLE
Difference between this and stamen/modestmaps-js?

### ISSUE THREAD

**Issue by ansis** [modestmaps/modestmaps-js#3]
There seems to be a significant amount of newer work in this repository. Is it a new home? Which repo would it be better to develop against?

**Comment by tmcw** [comment]
I intend to develop in this repository. The `/stamen` organization doesn't correctly represent modestmaps and the contributors, and `modestmaps-ui` should be easily found from modestmaps.

I [posted in the other one about making an organization](https://github.com/stamen/modestmaps-js/issues/113), got no response, just did it. I'm going to be porting the wiki and issues and backports over here.
