### ISSUE TITLE
Should setLayerAt tolerate layers added to the end of the layers array?

### ISSUE THREAD

**Issue by tmcw** [modestmaps/modestmaps-js#30]
/cc @migurski @shawnbot 

Right now if you have a map with a 'base layer' and an 'overlay' and you have a function that sets a new overlay, you need a bit of code like

``` javascript
if (map.getLayers().length == 1) {
  map.insertLayerAt(1, new layer());
} else {
  map.setLayerAt(1, new layer());
}
```

I can't find a good example of the set/insert semantics anywhere else to reference, but it seems like this function should be more permissive and tolerate 'setting' layers at higher indices than are present.

**Comment by migurski** [comment]
Would it error out, if for example you asked to set a layer that left a gap? Or would it not care, allowing you to set 0 and 2 but not 1. It seems like it should just let you leave gaps.

**Comment by tmcw** [comment]
Yeah, basically I'm seeing this relationship:

``` javascript
map.setLayerAt(0, layer);
// equals
map.layers[0] = layer;


map.insertLayerAt(0, layer);
// equals
map.layers.splice(0, 0, layer);
```

This will require a bit of logic in order to make them inserted in the right places, but I think it's worth it.
