### ISSUE TITLE
Place marker/bubble on map

### ISSUE THREAD

**Issue by mtx-z** [modestmaps/modestmaps-js#50]
Hello !
Firstly, thanks for this awesome plugin. I'm using it with awesome Stamen tiles =)
I made all my construction, and my map is working well with easey (to make smooth moves).

But i cannot success placing markers/bubble on specific coordinate on map.
I tried:

var loc = new MM.Location({lat: -27, lon: 152});
var loc1 = new MM.Location(30, 114);
var point = { x: 10, y: 20 };

But still nothing on the map, i found something with MM.Follower but it not works to. 
I'm simply trying to put BUBBLE on map (like in modestmaps example) or simple icon on a specific point. Thanks a lot !

**Comment by tmcw** [comment]
Hi,

You can either use https://github.com/mapbox/markers.js for this purpose. See an example here: http://mapbox.com/mapbox.js/example/single-marker/
