### ISSUE TITLE
http://modestmaps.com/examples/ - looks very broken

### ISSUE THREAD

**Issue by rossbruniges** [modestmaps/modestmaps-js#67]
While the homepage of http://modestmaps.com looks very promising having an example page like this
![Mozilla Firefox](https://f.cloud.github.com/assets/96099/302069/44f73b74-95f9-11e2-8b34-4844fe4173e9.jpg)
doesn't fill me with any confidence about investigating the app any further.

Is this a bug or coming soon?

**Comment by sethfitz** [comment]
This is a GitHub Pages configuration issue, not anything inherent to ModestMaps.

@tmcw the site root isn't generated with Jekyll, but `examples/` is; do you know what `_config.yml` needs to look like to handle this?  This is the error I get when I try to generate the site locally:

```
$ jekyll --pygments --no-lsi --safe
WARNING: Could not read configuration. Using defaults (and options).
    No such file or directory - /Users/seth/src/modestmaps/modestmaps-js/_config.yml
Building site: /Users/seth/src/modestmaps/modestmaps-js -> /Users/seth/src/modestmaps/modestmaps-js/_site
Liquid Exception: No such file or directory - /Users/seth/src/modestmaps/modestmaps-js/_includes in site.js
```

**Comment by rossbruniges** [comment]
Woohoo - now that looks much better :)

Thanks for sorting that out
